# permissions for end users to edit secretmirrors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmirror-editor-role
rules:
- apiGroups:
  - mirrors.kts.studio
  resources:
  - secretmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mirrors.kts.studio
  resources:
  - secretmirrors/status
  verbs:
  - get
