
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: secretmirrors.mirrors.kts.studio
spec:
  group: mirrors.kts.studio
  names:
    kind: SecretMirror
    listKind: SecretMirrorList
    plural: secretmirrors
    singular: secretmirror
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.source.name
      name: Source Name
      type: string
    - jsonPath: .spec.destination.namespace
      name: Dest Namespace
      type: string
    - jsonPath: .spec.destination.namespaceRegex
      name: Dest Namespace Regex
      type: string
    - jsonPath: .spec.pollPeriodSeconds
      name: Poll Period
      type: integer
    - jsonPath: .status.mirrorStatus
      name: Mirror Status
      type: string
    - jsonPath: .status.lastSyncTime
      name: Last Sync Time
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SecretMirror is the Schema for the secretmirrors API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SecretMirrorSpec defines the desired state of SecretMirror
            properties:
              destination:
                properties:
                  namespace:
                    type: string
                  namespaceRegex:
                    type: string
                type: object
              pollPeriodSeconds:
                format: int64
                type: integer
              source:
                properties:
                  name:
                    type: string
                type: object
            type: object
          status:
            description: SecretMirrorStatus defines the observed state of SecretMirror
            properties:
              lastSyncTime:
                format: date-time
                type: string
              mirrorStatus:
                default: Pending
                enum:
                - Pending
                - Active
                - Error
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .spec.source.type
      name: Source Type
      type: string
    - jsonPath: .spec.source.name
      name: Source Name
      type: string
    - jsonPath: .spec.destination.type
      name: Destination Type
      type: string
    - jsonPath: .spec.deletePolicy
      name: Delete Policy
      type: string
    - jsonPath: .spec.pollPeriodSeconds
      name: Poll Period
      type: integer
    - jsonPath: .status.mirrorStatus
      name: Mirror Status
      type: string
    - jsonPath: .status.lastSyncTime
      name: Last Sync Time
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        description: SecretMirror is the Schema for the secretmirrors API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SecretMirrorSpec defines the desired behaviour of Secret
              mirroring
            properties:
              deletePolicy:
                description: 'What to do with Secret objects created by a SecretMirror.
                  Two policies exist – delete (deletes all created secrets) and retain
                  (leaves them in the cluster). Default: delete'
                enum:
                - delete
                - retain
                type: string
              destination:
                description: SecretMirrorDestination defines where to sync a secret
                  data to
                properties:
                  namespaces:
                    description: An array of regular expressions to match namespaces
                      where to copy a source secret
                    items:
                      type: string
                    type: array
                  type:
                    default: namespaces
                    description: 'Destination type. Possible values — namespaces,
                      vault. Default: namespaces'
                    enum:
                    - namespaces
                    - vault
                    type: string
                  vault:
                    description: VaultSpec contains information of secret location
                    properties:
                      addr:
                        description: Addr specifies a Vault endpoint URL (e.g. https://vault.example.com)
                        type: string
                      auth:
                        description: VaultAuthSpec describes how to authenticate against
                          a Vault server
                        properties:
                          approle:
                            description: VaultAppRoleAuthSpec specifies approle-specific
                              auth data
                            properties:
                              appRolePath:
                                description: 'approle Vault prefix. Default: approle'
                                type: string
                              roleIDKey:
                                description: 'A key in the SecretRef which contains
                                  role-id value. Default: role-id'
                                type: string
                              secretIDKey:
                                description: 'A key in the SecretRef which contains
                                  secret-id value. Default: secret-id'
                                type: string
                              secretRef:
                                description: Reference to a Secret containing role-id
                                  and secret-id
                                properties:
                                  name:
                                    description: Name is unique within a namespace
                                      to reference a secret resource.
                                    type: string
                                  namespace:
                                    description: Namespace defines the space within
                                      which the secret name must be unique.
                                    type: string
                                type: object
                            type: object
                          token:
                            description: VaultTokenAuthSpec specifies token-specific
                              auth data
                            properties:
                              secretRef:
                                description: Reference to a Secret containing token
                                properties:
                                  name:
                                    description: Name is unique within a namespace
                                      to reference a secret resource.
                                    type: string
                                  namespace:
                                    description: Namespace defines the space within
                                      which the secret name must be unique.
                                    type: string
                                type: object
                              tokenKey:
                                description: 'A key in the SecretRef which contains
                                  token value. Default: token'
                                type: string
                            type: object
                        type: object
                      path:
                        description: Path specifies a vault secret path (e.g. secret/data/some-secret
                          or mongodb/creds/mymongo)
                        type: string
                    type: object
                type: object
              pollPeriodSeconds:
                description: 'How often to check for secret changes. Default: 180
                  seconds'
                format: int64
                type: integer
              source:
                description: SecretMirrorSource defines where to extract a secret
                  data from
                properties:
                  name:
                    type: string
                  type:
                    default: secret
                    enum:
                    - secret
                    - vault
                    type: string
                  vault:
                    description: VaultSpec contains information of secret location
                    properties:
                      addr:
                        description: Addr specifies a Vault endpoint URL (e.g. https://vault.example.com)
                        type: string
                      auth:
                        description: VaultAuthSpec describes how to authenticate against
                          a Vault server
                        properties:
                          approle:
                            description: VaultAppRoleAuthSpec specifies approle-specific
                              auth data
                            properties:
                              appRolePath:
                                description: 'approle Vault prefix. Default: approle'
                                type: string
                              roleIDKey:
                                description: 'A key in the SecretRef which contains
                                  role-id value. Default: role-id'
                                type: string
                              secretIDKey:
                                description: 'A key in the SecretRef which contains
                                  secret-id value. Default: secret-id'
                                type: string
                              secretRef:
                                description: Reference to a Secret containing role-id
                                  and secret-id
                                properties:
                                  name:
                                    description: Name is unique within a namespace
                                      to reference a secret resource.
                                    type: string
                                  namespace:
                                    description: Namespace defines the space within
                                      which the secret name must be unique.
                                    type: string
                                type: object
                            type: object
                          token:
                            description: VaultTokenAuthSpec specifies token-specific
                              auth data
                            properties:
                              secretRef:
                                description: Reference to a Secret containing token
                                properties:
                                  name:
                                    description: Name is unique within a namespace
                                      to reference a secret resource.
                                    type: string
                                  namespace:
                                    description: Namespace defines the space within
                                      which the secret name must be unique.
                                    type: string
                                type: object
                              tokenKey:
                                description: 'A key in the SecretRef which contains
                                  token value. Default: token'
                                type: string
                            type: object
                        type: object
                      path:
                        description: Path specifies a vault secret path (e.g. secret/data/some-secret
                          or mongodb/creds/mymongo)
                        type: string
                    type: object
                type: object
            type: object
          status:
            description: SecretMirrorStatus defines the observed state of SecretMirror
            properties:
              lastSyncTime:
                description: Timestamp of last successful mirrorring
                format: date-time
                type: string
              mirrorStatus:
                default: Pending
                description: Mirroring status - Active, Pending or Error
                enum:
                - Pending
                - Active
                - Error
                type: string
              vaultSource:
                description: VaultSourceStatusSpec describes Vault-specific status
                properties:
                  leaseDuration:
                    description: Contains lease duration of a Vault dynamic secret
                    type: integer
                  leaseID:
                    description: Contains LeaseID of a Vault dynamic secret
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
